aws-samples/generative-bi-using-rag

application/pages/1_🌍_Natural_Language_Querying.py, application/utils/llm.py, application/utils/prompt.py
=> support claude3 inference

application/nlq/data_access/database.py
=> add redshift db mapping

README.md, README_CN.md
#4 
Replaced dnf with yum for package installation
=> update readme to support AL2 deployment

application/Dockerfile, application/docker-compose.yml, application/requirements.txt, application/utils/apis.py
Revised code after probe scan. 
=> fix for probe scan

application/nlq/business/suggested_question.py, application/nlq/data_access/dynamo_suggested_question.py, application/pages/1_🌍_Natural_Language_Querying.py, application/pages/7_🖥_Suggested_Question_Management.py, application/utils/constant.py, application/utils/llm.py, application/utils/prompt.py
Add 3 suggested question and related management page
=> feat: add suggested question

application/pages/1_🌍_Natural_Language_Querying.py, application/pages/7_🖥_Suggested_Question_Management.py
Fix the issue that prompt not shown at the first loading
=> fix: prompt not shown at the first loading

application/nlq/business/vector_store.py
=> fix some index name

application/pages/1_🌍_Natural_Language_Querying.py
- add is_visualization_config_changed
=> add is_visualization_config_changed

README.md, README_CN.md, application/Index.py, application/utils/prompts/guidance_prompt.py, application/utils/prompts/table_prompt.py
=> Revert "change some code "

application/.env.template, application/nlq/data_access/dynamo_connection.py
=> fix region problem

application/api/enum.py, application/api/main.py, application/api/schemas.py, application/api/service.py, application/static/RESTful.html, application/static/WebSocket.html
=> feat: Add session id for WebSocket

application/pages/1_🌍_Natural_Language_Querying.py
=> fix score error

.gitignore, README.md, source/model/embedding/code/model.py, source/model/embedding/code/requirements.txt, source/model/embedding/code/serving.properties, source/model/embedding/model/bge-m3_model.py, source/model/embedding/model/model.sh, source/model/embedding/model/serving.properties, source/model/internlm/code/model.py, source/model/internlm/code/requirements.txt, source/model/internlm/code/serving.properties, source/model/internlm/model/internlm2-chat-7b_model.py, source/model/internlm/model/model.sh, source/model/internlm/model/serving.properties, source/model/prepare_model.sh, source/model/sqlcoder/code/model.py, source/model/sqlcoder/code/requirements.txt, source/model/sqlcoder/code/serving.properties, source/model/sqlcoder/model/model.sh, source/model/sqlcoder/model/serving.properties, source/model/sqlcoder/model/sqlcoder-7b-2_model.py, source/resources/lib/main-stack.ts, source/resources/lib/model/llm-stack.ts
=> feat: add sagemaker endpoint inference and cdk code

application/api/exception_handler.py, application/api/main.py, application/api/service.py, application/nlq/business/connection.py, application/nlq/business/profile.py, application/nlq/business/suggested_question.py, application/nlq/business/vector_store.py, application/nlq/data_access/database.py, application/nlq/data_access/dynamo_connection.py, application/nlq/data_access/dynamo_profile.py, application/nlq/data_access/dynamo_suggested_question.py, application/pages/1_🌍_Natural_Language_Querying.py, application/pages/3_🪙_Data_Profile_Management.py, application/pages/4_📚_Index_Management.py, application/pages/5_🖥_Schema_Management.py, application/pages/6_📚_Entity_Management.py, application/pages/7_🖥_Suggested_Question_Management.py, application/requirements-api.txt, application/requirements.txt, application/utils/apis.py, application/utils/llm.py, application/utils/opensearch.py, application/utils/prompts/generate_prompt.py
=> removed loguru

application/nlq/business/vector_store.py, application/requirements-api.txt, application/requirements.txt, application/utils/prompt.py
=> fix redshift error

application/pages/1_🌍_Natural_Language_Querying.py, application/requirements-api.txt
=> change intent False to True

application/pages/1_🌍_Natural_Language_Querying.py, application/utils/prompts/generate_prompt.py
=> fix some error

application/nlq/business/nlq_chain.py
=> change sql response

application/.streamlit/config.toml, application/Index.py, application/config_files/stauth_config.yaml, application/pages/1_🌍_Natural_Language_Querying.py, application/pages/2_🪙_Data_Connection_Management.py, application/pages/3_🪙_Data_Profile_Management.py, application/pages/4_📚_Index_Management.py, application/pages/5_🪙_Schema_Description_Management.py, application/pages/6_📚_Entity_Management.py, application/pages/7_🖥_Suggested_Question_Management.py, application/pages/8_📚_Agent_Cot_Management.py, application/pages/mainpage.py, application/requirements.txt, application/utils/navigation.py
Add log in UI with default credential.
=> Add log in UI

README.md, README_CN.md, application/pages/1_🌍_Natural_Language_Querying.py, application/pages/8_📚_Agent_Cot_Management.py, application/utils/llm.py, application/utils/prompt.py, application/utils/prompts/generate_prompt.py, application/utils/tool.py
=> add agent cot function

application/pages/1_🌍_Natural_Language_Querying.py, application/utils/llm.py, application/utils/prompts/generate_prompt.py
=> add llama3 70b

application/nlq/business/nlq_chain.py, application/nlq/data_access/database.py, application/pages/1_🌍_Natural_Language_Querying.py
=> add resshift schema

application/nlq/business/profile.py, application/nlq/data_access/dynamo_profile.py, application/pages/5_🪙_Prompt_Management.py, application/utils/prompts/generate_prompt.py
New prompt management page now can select by 8 prompt type and LLM models.
=> Add prompt management page with different types and models

application/api/service.py, application/nlq/business/profile.py, application/pages/1_🌍_Generative_BI_Playground.py, application/utils/llm.py, application/utils/prompts/generate_prompt.py, application/utils/text_search.py
Use DynamoDB prompts in text2sql and intent search
=> Use DynamoDB prompts in text2sql and intent search

application/api/service.py, application/pages/1_🌍_Generative_BI_Playground.py, application/utils/llm.py, application/utils/prompts/generate_prompt.py
Use DynamoDB prompts in knowledge and agent COT
=> Use DynamoDB prompts in knowledge and agent COT

application/api/main.py, application/api/schemas.py, application/api/service.py, application/main.py, application/pages/5_🪙_Prompt_Management.py, application/utils/llm.py, application/utils/prompts/generate_prompt.py
=> add model select show type

application/pages/5_🪙_Prompt_Management.py, application/utils/prompts/check_prompt.py
Add prompt syntax check with error message in prompt management page
=> Add prompt syntax check with error message in prompt management page

README.md, README_CN.md, application/Dockerfile, application/api/main.py, application/api/schemas.py, application/api/service.py, application/nlq/business/vector_store.py, application/nlq/data_access/dynamo_query_log.py, application/nlq/data_access/opensearch.py, application/pages/1_🌍_Generative_BI_Playground.py, application/pages/5_🪙_Prompt_Management.py, application/pages/6_📚_Index_Management.py, application/pages/7_📚_Entity_Management.py, application/pages/8_📚_Agent_Cot_Management.py
=> change show size 5000

application/nlq/data_access/dynamo_profile.py
Hot fix: ignore unused attributes in profile fetched from DynamoDB
=> Hot fix: ignore unused attributes in profile fetched from DynamoDB

application/docker-compose-build.sh, application/nlq/data_access/dynamo_profile.py, application/pages/1_🌍_Generative_BI_Playground.py, application/pages/3_🪙_Data_Profile_Management.py, application/utils/env_var.py, application/utils/llm.py
- [fix bug when create data profile](https://github.com/aws-samples/generative-bi-using-rag/commit/a8cb6f814e9e0d384f0b8769d2ad5562bd28a126)
=> fix bug when create data profile

application/api/service.py, application/pages/1_🌍_Generative_BI_Playground.py, application/static/WebSocket.html
- add hava_session_state_flag judge
=> add hava_session_state_flag judge

application/pages/1_🌍_Generative_BI_Playground.py
- [update init hava_session_state_flag judge](https://github.com/aws-samples/generative-bi-using-rag/commit/f2acf18ac190c6e3d555af7930171ea0a1c5ab1a)
=> update init hava_session_state_flag judge

README.md, README_CN.md, application/config_files/stauth_config.yaml
Remove preset credential in config
=> Remove preset credential in config

report-front-end/package.json, report-front-end/src/common/api/WebSocket.ts, report-front-end/src/components/chatbot-panel/chat-input-panel.tsx, report-front-end/src/components/chatbot-panel/chat-message.tsx, report-front-end/src/components/chatbot-panel/chat.module.scss, report-front-end/src/components/chatbot-panel/chat.tsx, report-front-end/src/components/chatbot-panel/custom-questions.tsx, report-front-end/src/components/chatbot-panel/suggested-questions.tsx, report-front-end/src/components/chatbot-panel/types.ts
=> add websocket

report-front-end/src/app.tsx, report-front-end/src/common/api/WebSocket.ts, report-front-end/src/components/chatbot-panel/chat-input-panel.tsx, report-front-end/src/components/chatbot-panel/custom-questions.tsx, report-front-end/src/components/chatbot-panel/suggested-questions.tsx, report-front-end/src/components/config-panel/index.tsx, report-front-end/src/components/config-panel/store.ts, report-front-end/src/components/config-panel/types.ts, report-front-end/src/pages/login-page/index.tsx
=> add context window

application/generate_streamlit_password.py, application/pages/1_🌍_Generative_BI_Playground.py
- [add streamlit password generate](https://github.com/aws-samples/generative-bi-using-rag/commit/752448f6f9c43fb2fc3d332e29d62434b0687e69)
=> add streamlit password generate

report-front-end/.env, report-front-end/src/common/api/WebSocket.ts
=> update environment variable

application/main.py, source/resources/lib/aos/aos-stack.ts, source/resources/lib/ecs/ecs-stack.ts, source/resources/lib/main-stack.ts
=> updated cdk

source/resources/bin/main.ts, source/resources/lib/.env, source/resources/lib/aos/aos-stack.ts, source/resources/lib/cognito/cognito-stack.ts, source/resources/lib/ecs/ecs-stack.ts, source/resources/lib/main-stack.ts, source/resources/lib/rds/rds-stack.ts
=> polished the cdk and added cognito

README.md, source/resources/README.md
=> Readme update

application/utils/env_var.py
- [change opensearch init](https://github.com/aws-samples/generative-bi-using-rag/commit/c89ca6e06edc23b07ceb25d90b5d979e9716e3a7)
=> change opensearch init

application/.env.template, application/utils/env_var.py
=> hotfix aksk bug

source/resources/lib/ecs/ecs-stack.ts
=> frontend bug fix. Add environment file before docker build

report-front-end/.env.template
=> add .env file

README.md, application/pages/1_🌍_Generative_BI_Playground.py
- [change doc url](https://github.com/aws-samples/generative-bi-using-rag/commit/da52560fe45b9354fadae236f841db4f83a40590)
=> change doc url

report-front-end/package.json, report-front-end/src/common/api/WebSocket.ts, report-front-end/src/common/constant/constants.ts, report-front-end/src/pages/login-page/aws-config.ts, report-front-end/vite.config.ts, source/resources/lib/ecs/ecs-stack.ts
=> Wangzt dev

application/utils/env_var.py
=> fix some bug  for env

report-front-end/Dockerfile, report-front-end/docker-entry.sh
=> frontend change

report-front-end/docker-entry.sh
=> env bug fix

application/docker-compose.yml, source/resources/lib/ecs/ecs-stack.ts
- [add sagemaker policy](https://github.com/aws-samples/generative-bi-using-rag/commit/de7343faee1d78ce456d09b29d37e3afdd98f3f6)
=> add sagemaker policy

application/pages/3_🪙_Data_Profile_Management.py, application/pages/4_🪙_Schema_Description_Management.py, application/pages/5_🪙_Prompt_Management.py, application/pages/6_📚_Index_Management.py, application/pages/7_📚_Entity_Management.py, application/pages/8_📚_Agent_Cot_Management.py
- [fix some bug](https://github.com/aws-samples/generative-bi-using-rag/commit/9dd887b3807fc9640565dd018e044034190aa3a3)
=> fix some bug

application/pages/6_📚_Index_Management.py, application/pages/7_📚_Entity_Management.py
- [add batch entity upload](https://github.com/aws-samples/generative-bi-using-rag/commit/78a69d78731b31f198b0d9642a8b2cd3d555ca77)
=> add batch entity upload

source/resources/lib/ecs/ecs-stack.ts, source/resources/lib/main-stack.ts
=> fixed some inconsistency in cdk

report-front-end/src/components/chatbot-panel/chat-input-panel.tsx
=> Enable Shift + Enter to query

report-front-end/src/components/chatbot-panel/chat-message.tsx, report-front-end/src/components/config-panel/index.tsx
=> Add pagination

report-front-end/src/components/chatbot-panel/chat-input-panel.tsx
=> Enter to send a message

application/utils/navigation.py
- [fix expiry_days bug](https://github.com/aws-samples/generative-bi-using-rag/commit/9fe08be7b52fa92a42405806df0f6fe983a1cf57)
=> fix expiry_days bug

application/pages/4_🪙_Schema_Description_Management.py
- [fix profile bug](https://github.com/aws-samples/generative-bi-using-rag/commit/ecdaf0920c122195f9c49795eb892e0d3d7f80cd)
=> fix profile bug

report-front-end/src/app.tsx, report-front-end/src/common/helpers/types.ts, report-front-end/src/components/alert-msg/index.tsx, report-front-end/src/components/alert-msg/style.scss, report-front-end/src/components/chatbot-panel/chat-message.tsx, report-front-end/src/components/config-panel/index.tsx, report-front-end/src/components/config-panel/style.scss, report-front-end/src/pages/chatbot-page/playground.tsx
=> Add save button and logic

application/utils/prompts/generate_prompt.py
- [change rewrite prompt](https://github.com/aws-samples/generative-bi-using-rag/commit/0071ea6bbc7105e8a10e21b9354a778371d224cc)
=> change rewrite prompt

report-front-end/src/app.tsx, report-front-end/src/common/api/API.ts, report-front-end/src/common/constant/constants.ts, report-front-end/src/common/helpers/store.ts, report-front-end/src/common/helpers/types.ts, report-front-end/src/components/chatbot-panel/chat-input-panel.tsx, report-front-end/src/components/chatbot-panel/chat.tsx, report-front-end/src/components/chatbot-panel/custom-questions.tsx, report-front-end/src/components/chatbot-panel/suggested-questions.tsx, report-front-end/src/components/config-panel/index.tsx
=> Add localstorage

application/requirements-api.txt, application/requirements.txt
- [add openpyxl](https://github.com/aws-samples/generative-bi-using-rag/commit/efc16b7ebdd913f7431e2f1ac7ff22c77d4621a2)
=> add openpyxl

report-front-end/vite.config.ts
=> import env.local

report-front-end/.env
=> remove logo

application/docker-compose.yml
=> add frontend to docker composer

report-front-end/src/components/config-panel/index.tsx
=> add contextWindow

application/nlq/data_access/database.py, application/pages/2_🪙_Data_Connection_Management.py, application/requirements.txt
I Created this Issue .
https://github.com/aws-samples/generative-bi-using-rag/issues/152
I‘m update code tosupport the StarRocks database
=> Add new feature: support for StarRocks

application/api/service.py, application/nlq/data_access/dynamo_query_log.py
- [fix log issue](https://github.com/aws-samples/generative-bi-using-rag/commit/e9136f04c0bed643d13678e05e1c19e666b3775d)
=> fix log issue

application/config_files/stauth_config.yaml
- [change expiry_days](https://github.com/aws-samples/generative-bi-using-rag/commit/6dca7fd02b8faefcc4f632935972ca3574a7de89)
=> change expiry_days

application/nlq/data_access/dynamo_suggested_question.py
=> import error

application/nlq/data_access/database.py, application/pages/2_🪙_Data_Connection_Management.py, application/requirements-api.txt, application/requirements.txt, application/utils/prompt.py, application/utils/prompts/generate_prompt.py
=> 添加clickhouse支持

README.md, application/api/main.py, application/main.py
Changes for authentication
Authentication for HTTP request and WebSocket request.
=> Changes for authentication

report-front-end/Dockerfile, report-front-end/docker-entry.sh, report-front-end/nginx.template
=> nginx 配置/api

application/nlq/business/profile.py, application/pages/3_🪙_Data_Profile_Management.py, application/pages/4_🪙_Schema_Description_Management.py, application/pages/5_🪙_Prompt_Management.py, application/pages/6_📚_Index_Management.py, application/pages/7_📚_Entity_Management.py, application/pages/8_📚_Agent_Cot_Management.py
[fix current profile select](https://github.com/aws-samples/generative-bi-using-rag/commit/fe9b5a36da3d6878a1d00caefe73302a65c9556e)
=> fix current profile select

application/pages/6_📚_Index_Management.py, application/pages/7_📚_Entity_Management.py
- [fix batch entity insert](https://github.com/aws-samples/generative-bi-using-rag/commit/96dec46a60c6c6ea1808e99709f30ea8fb93d5d7)
=> fix batch entity insert

application/api/main.py, application/main.py
update the cookie key to dlunifiedtoken
=> update for jwtToken

application/docker-compose.yml, application/nlq/data_access/database.py, application/utils/prompt.py
=> 优化clickhouse提示词和建表语句

application/nlq/business/profile.py, application/pages/3_🪙_Data_Profile_Management.py, application/pages/4_🪙_Schema_Description_Management.py, application/pages/5_🪙_Prompt_Management.py, application/pages/6_📚_Index_Management.py, application/pages/7_📚_Entity_Management.py, application/pages/8_📚_Agent_Cot_Management.py, source/resources/bin/main.ts, source/resources/tsconfig.json
- [fix batch upload slow](https://github.com/aws-samples/generative-bi-using-rag/commit/c40901a919e07f605087d21214fa5fdf2186c7c1)
=> fix batch upload slow

application/api/service.py
[fix data_visualization nan](https://github.com/aws-samples/generative-bi-using-rag/commit/16351ef58049e1a4d9cadcd2d71c029df0256f0e)
=> fix data_visualization nan

application/api/service.py
- [add user id decode](https://github.com/aws-samples/generative-bi-using-rag/commit/bdf512fc09a26be4b35ed599e2dd77b07ca383b7)
=> add user id decode

application/api/main.py, application/api/service.py
- [fix userid issue](https://github.com/aws-samples/generative-bi-using-rag/commit/4fb30e6990a1c85b747e1c83c56d6ef75fe057aa)
=> fix userid issue

source/resources/lib/main-stack.ts
- [fix china deploy](https://github.com/aws-samples/generative-bi-using-rag/commit/37358a1dbaefba4fdd70b81dcfb5ce0319b4d1b3)
=> fix china deploy

application/pages/1_🌍_Generative_BI_Playground.py, application/utils/constant.py
- [change model order](https://github.com/aws-samples/generative-bi-using-rag/commit/47fa811b4a6cac8ff45c9374c3f64c9af73baca8)
=> change model order

application/Dockerfile, application/Dockerfile-api, report-front-end/Dockerfile, source/resources/lib/ecs/ecs-stack.ts
- [fix china cdk deploy npm source](https://github.com/aws-samples/generative-bi-using-rag/commit/906559b3295e57e52e4215c462d0f1b7e0c410f7)
=> add docker aws region and fix china cdk deploy npm source

application/pages/1_🌍_Generative_BI_Playground.py
- [add replay ask](https://github.com/aws-samples/generative-bi-using-rag/commit/9ecdf15b5610155c90e6ab6641b7a2000c84a446)
=> add replay ask

application/nlq/data_access/opensearch.py, application/pages/6_📚_Index_Management.py, application/pages/7_📚_Entity_Management.py, application/pages/8_📚_Agent_Cot_Management.py
- [change max read sql](https://github.com/aws-samples/generative-bi-using-rag/commit/064d14610d1966de0fb625c15af1220e7603ec79)
=> change max read sql

report-front-end/src/common/api/WebSocket.ts, report-front-end/src/components/chatbot-panel/chat-message.tsx
=> show table without pagination

application/api/enum.py, application/api/service.py, application/nlq/data_access/database.py, application/pages/2_🪙_Data_Connection_Management.py, application/requirements-api.txt, application/requirements.txt, application/utils/prompt.py, application/utils/prompts/generate_prompt.py
1. support clickhouse db as datasource
2. return meaningful error when profile name not found for qa ask API
*Issue #, if available:* 
#204 
=> support clickhouse db as datasource

application/nlq/business/vector_store.py, application/pages/1_🌍_Generative_BI_Playground.py, application/requirements-api.txt, application/requirements.txt, application/utils/env_var.py, application/utils/llm.py, source/resources/bin/main.ts, source/resources/cdk-config.json, source/resources/lib/ecs/ecs-stack.ts, source/resources/lib/main-stack.ts, source/resources/lib/rds/rds-stack.ts, source/resources/lib/vpc/vpc-stack.ts
[add segamaker env](https://github.com/aws-samples/generative-bi-using-rag/commit/34370bb2e5418faa180987ceca8edea448658ea2)
=> add segamaker env

report-front-end/src/components/chatbot-panel/chat-message.tsx
=> show total table with modal

report-front-end/src/common/api/API.ts, report-front-end/src/common/api/WebSocket.ts, report-front-end/src/common/helpers/store.ts, report-front-end/src/common/hooks/use-navigation-panel-state.ts
=> add log print

report-front-end/src/common/api/WebSocket.ts
=> add error message

application/nlq/business/vector_store.py
[change code for segamaker](https://github.com/aws-samples/generative-bi-using-rag/commit/f47ee3bd4d1cb7f0722c7f17b26d482ac8241276)
=> change code for segamaker

source/resources/lib/main-stack.ts
=> Update main-stack.ts to fix cognito bug

application/pages/1_🌍_Generative_BI_Playground.py
[fix explain_gen_process_flag bug](https://github.com/aws-samples/generative-bi-using-rag/commit/5139a55f7226bdaee492459f888610bd56a9c733)
=> fix explain_gen_process_flag bug

report-front-end/.env, source/resources/lib/main-stack.ts
[change Login configuration](https://github.com/aws-samples/generative-bi-using-rag/commit/4bad91882c15bc64020aae401caef6c0fc0cac2d)
=> change Login configuration

report-front-end/src/components/session-panel/sessions.tsx
=> switch current session

application/nlq/data_access/database.py, application/pages/2_🪙_Data_Connection_Management.py, application/requirements-api.txt, application/requirements.txt, application/utils/llm.py, application/utils/prompt.py, application/utils/prompts/generate_prompt.py
Add one feature about support Bigquery in database connection.
- Support Bigquery database connection and retrieve DDL of tables in Bigquery
- Add some init prompts for Bigquery
=> feature: support bigquery connection

application/api/enum.py, application/api/main.py, application/api/schemas.py, application/api/service.py, application/main.py, application/nlq/business/log_store.py, application/nlq/data_access/dynamo_query_log.py, application/pages/1_🌍_Generative_BI_Playground.py, application/requirements.txt, application/utils/env_var.py, application/utils/llm.py, application/utils/tool.py
[Add multiple rounds of historical dialogue display](https://github.com/aws-samples/generative-bi-using-rag/commit/b6792a883be4486854b7d00e25a97e5a689063b9)
=> Add multiple rounds of historical dialogue display

report-front-end/src/components/session-panel/session.tsx
=> remove unused code

application/api/service.py
[fix user id](https://github.com/aws-samples/generative-bi-using-rag/commit/8d738e5de7f7fc8cb51b215661f6e988648b9c6f)
=> fix user id

application/pages/6_📚_Index_Management.py
[fix sql bug](https://github.com/aws-samples/generative-bi-using-rag/commit/e2dc7c62ec51e61f8c0476aad7ff787721ed91a5)
=> fix sql bug

application/api/main.py, application/nlq/business/vector_store.py, application/nlq/data_access/opensearch.py, application/pages/7_📚_Entity_Management.py, application/utils/opensearch.py
[change entity index](https://github.com/aws-samples/generative-bi-using-rag/commit/f6f8551959113de66a6b2a26a97b42832eb903f6)
=> change entity index

application/api/main.py, application/nlq/business/log_store.py, application/nlq/data_access/opensearch_query_log.py
[change fun name and add time_str for session](https://github.com/aws-samples/generative-bi-using-rag/commit/fedda78105ca80ddcc05b30ed7d251e5a176cc5a)
=> change fun name and add time_str for session

application/utils/llm.py, application/utils/prompt.py, application/utils/prompts/generate_prompt.py
=> fix query rewrite bug

report-front-end/.env
[fix Cognito](https://github.com/aws-samples/generative-bi-using-rag/commit/b2b82770849460217c48a5039b1b99f911e37f8e)
=> fix Cognito

application/utils/prompts/generate_prompt.py
[change prompt](https://github.com/aws-samples/generative-bi-using-rag/commit/fe8c7a9f346a9470a9517c22f9aa8bb3d6586c35)
=> change prompt

report-front-end/.env
[change VITE_LOGIN_TYPE](https://github.com/aws-samples/generative-bi-using-rag/commit/e46cc2e53d3a818dcdd4c923cc1ce5faa0d0777c)
=> change VITE_LOGIN_TYPE

application/Index.py, application/main.py, application/nlq/data_access/database.py, application/requirements-api.txt, application/requirements.txt, application/utils/llm.py, application/utils/tool.py, report-front-end/.env, report-front-end/Dockerfile
[add code update](https://github.com/aws-samples/generative-bi-using-rag/commit/cf18002d1a822913c3923389a4108f3e4d3641ad)
=> add code update

report-front-end/src/app.tsx, report-front-end/src/common/api/API.ts, report-front-end/src/common/api/WebSocket.ts, report-front-end/src/common/constant/constants.ts, report-front-end/src/components/top-navigation/index.tsx, report-front-end/src/main.tsx, report-front-end/src/pages/login-page/cognito-login-page/index.tsx
=> ui-feat: add jwt token to requests only when cognito login

application/Index.py, application/api/main.py, application/api/schemas.py, application/api/service.py, application/main.py, application/nlq/business/log_store.py, application/nlq/business/vector_store.py, application/nlq/core/chat_context.py, application/nlq/core/state.py, application/nlq/core/state_machine.py, application/nlq/data_access/dynamo_connection.py, application/nlq/data_access/dynamo_query_log.py, application/nlq/data_access/opensearch_query_log.py, application/pages/1_🌍_Generative_BI_Playground.py, application/pages/7_📚_Entity_Management.py, application/requirements.txt, application/utils/navigation.py, application/utils/opensearch.py, application/utils/prompts/generate_prompt.py, application/utils/text_search.py, application/utils/tool.py
[add new state machine code](https://github.com/aws-samples/generative-bi-using-rag/commit/7f195f7af0cca7f50ee704aa768ea42bcb59c79f)
=> add new state machine code

application/main.py, application/nlq/data_access/dynamo_connection.py, application/utils/auth.py
[add response_error](https://github.com/aws-samples/generative-bi-using-rag/commit/9eb83f64ce0b47cc1d1b93bf9766de7f05fceb43)
=> add response_error

application/main.py, application/nlq/data_access/dynamo_connection.py, application/nlq/data_access/opensearch_query_log.py, application/utils/auth.py, application/utils/env_var.py, application/utils/opensearch.py, source/resources/lib/ecs/ecs-stack.ts
[add index init](https://github.com/aws-samples/generative-bi-using-rag/commit/9d2420cb62e01122b0eec1dece07c14b0f541eaa)
=> add index init

source/resources/lib/ecs/ecs-stack.ts
[add Platform](https://github.com/aws-samples/generative-bi-using-rag/commit/9c33d092b3f335cd0826833588982518130ae1bd)
=> add Platform

source/resources/lib/ecs/ecs-stack.ts
[add Platform.LINUX_AMD64](https://github.com/aws-samples/generative-bi-using-rag/commit/df343e72d5cdb455b4af3aead935b0cc1b1b1fdb)
=> add Platform.LINUX_AMD64

application/utils/tool.py
[change convert_timestamps_to_str](https://github.com/aws-samples/generative-bi-using-rag/commit/63786c88bc39940f92472ec1b4b0544d489989ff)
=> change convert_timestamps_to_str

application/nlq/core/state_machine.py, application/pages/1_🌍_Generative_BI_Playground.py
[add error info show](https://github.com/aws-samples/generative-bi-using-rag/commit/04346ee0a071b8111a0fd43a22ca6f8476a3a779)
=> add error info show

application/pages/1_🌍_Generative_BI_Playground.py
[fix dup key](https://github.com/aws-samples/generative-bi-using-rag/commit/82644dfd2e825dbc19c17a534350d57a83397110)
=> fix dup key

application/pages/1_🌍_Generative_BI_Playground.py, application/pages/3_🪙_Data_Profile_Management.py, application/pages/4_🪙_Schema_Description_Management.py, application/pages/5_🪙_Prompt_Management.py
[add profile select](https://github.com/aws-samples/generative-bi-using-rag/commit/e771d39f0d7abb779d79b6856a1d8e5c8dfa971b)
=> add profile select

application/pages/1_🌍_Generative_BI_Playground.py, application/pages/3_🪙_Data_Profile_Management.py
[add update_profile](https://github.com/aws-samples/generative-bi-using-rag/commit/f4dbd94223caa3238a34b528daf93f5b34ec5b31)
=> add update_profile

application/pages/3_🪙_Data_Profile_Management.py, application/pages/4_🪙_Schema_Description_Management.py, application/pages/5_🪙_Prompt_Management.py, application/pages/6_📚_Index_Management.py, application/pages/7_📚_Entity_Management.py, application/pages/8_📚_Agent_Cot_Management.py, application/utils/text_search.py
[add st.session_state.ner_refresh_view](https://github.com/aws-samples/generative-bi-using-rag/commit/36becba60927e289051209dd2ff520919915367f)
=> add st.session_state.ner_refresh_view

application/pages/7_📚_Entity_Management.py, application/pages/8_📚_Agent_Cot_Management.py
[fix update_profile problem](https://github.com/aws-samples/generative-bi-using-rag/commit/58108d3a9f24bf8a0667358cb80228f1a37a5124)
=> fix update_profile problem

application/api/service.py, application/nlq/business/model.py, application/nlq/data_access/dynamo_model.py, application/utils/llm.py
=> change for sagemaker endpoint invocation

application/nlq/data_access/database.py, application/pages/2_🪙_Data_Connection_Management.py, application/requirements-api.txt, application/requirements.txt, application/utils/prompt.py, application/utils/prompts/generate_prompt.py
[add db_type hive](https://github.com/aws-samples/generative-bi-using-rag/commit/f267fba6e94fddb1daf10c88056fcd0ad64591c2)
=> add db_type hive

source/resources/lib/ecs/ecs-stack.ts
[add secretsmanager PutSecretValue](https://github.com/aws-samples/generative-bi-using-rag/commit/9bf3c12f748bfcb5a0f82465509f66e7b4b11047)
=> add secretsmanager PutSecretValue

application/api/service.py, application/nlq/business/model.py, application/nlq/business/profile.py, application/nlq/core/state_machine.py, application/nlq/data_access/dynamo_model.py, application/pages/1_🌍_Generative_BI_Playground.py, application/pages/2_🪙_Data_Connection_Management.py, application/pages/9_🪙_SageMaker_Model_Management.py, application/utils/llm.py, application/utils/navigation.py, application/utils/prompts/generate_prompt.py
[add sagemaker endpoint](https://github.com/aws-samples/generative-bi-using-rag/commit/5e4c88231e2e88b69ce6196d15c6122e373e0c79)
=> add sagemaker endpoint config

application/utils/tool.py
…tamp and Datetime.date
add Custom serialization function
=> add Custom serialization function 

application/api/main.py, application/api/service.py
[add serialize_timestamp for time date](https://github.com/aws-samples/generative-bi-using-rag/commit/483d5ee16fa64533e7c08e13808daf4aa12070bc)
=> add serialize_timestamp for time date

application/api/service.py, application/pages/7_📚_Entity_Management.py
[fix add_entity_dimension_batch_sample error](https://github.com/aws-samples/generative-bi-using-rag/commit/94dcfb293b68d4e4f98f99f5458462b6cecdcca3)
=> fix add_entity_dimension_batch_sample error

source/resources/lib/ecs/ecs-stack.ts
[add bedrock secretsmanager police](https://github.com/aws-samples/generative-bi-using-rag/commit/03826902515fb09615c28de32317ff0935e07dde)
=> add bedrock secretsmanager police

application/api/main.py, application/api/schemas.py, application/api/service.py, application/nlq/business/profile.py, application/nlq/core/state.py, application/nlq/core/state_machine.py, application/pages/1_🌍_Generative_BI_Playground.py, application/pages/7_📚_Entity_Management.py, application/pages/9_🪙_SageMaker_Model_Management.py, application/utils/llm.py, application/utils/tool.py, source/resources/lib/ecs/ecs-stack.ts, source/resources/lib/redshift/redshfit-stack.ts
[add entity select](https://github.com/aws-samples/generative-bi-using-rag/commit/2e29aebf4e1eb0d113731a34c56f3277678077ca)
=> add entity select

application/api/service.py, application/nlq/core/state_machine.py, application/pages/6_📚_Index_Management.py, application/pages/7_📚_Entity_Management.py
[change state for entity select](https://github.com/aws-samples/generative-bi-using-rag/commit/175399eee223177d222ec0033d836be90466aa22)
=> change state for entity select

application/api/service.py, application/nlq/core/state_machine.py
[update entity delete](https://github.com/aws-samples/generative-bi-using-rag/commit/2762c92f6ec91e7b5446bcd733dcf42411331de1)
=> update entity delete

application/pages/9_🪙_SageMaker_Model_Management.py
[change model list](https://github.com/aws-samples/generative-bi-using-rag/commit/c5adfd88584fd76a96a3d211cb655d71b7800532)
=> change model list

application/api/schemas.py, application/api/service.py
[update session id](https://github.com/aws-samples/generative-bi-using-rag/commit/74f8a5a2795bd52f234ec2b8b99866cb6c900eca)
=> update session id

application/nlq/data_access/opensearch.py, application/utils/prompts/check_prompt.py
[add create_vector_embedding_with_sagemaker for search](https://github.com/aws-samples/generative-bi-using-rag/commit/087ba14e7650e5982c5e07866160ce2114b69b08)
=> V1.7.0 dev

application/nlq/data_access/database.py, application/pages/2_🪙_Data_Connection_Management.py
=> athena support

application/nlq/data_access/database.py, application/pages/2_🪙_Data_Connection_Management.py, application/requirements-api.txt, application/requirements.txt, application/utils/llm.py, application/utils/prompt.py, application/utils/prompts/generate_prompt.py
[add big query](https://github.com/aws-samples/generative-bi-using-rag/commit/71614b8301a9a0e5ee5b917ee2e036be9afbc0f7)
=> add big query

application/api/service.py
[add user_query_history](https://github.com/aws-samples/generative-bi-using-rag/commit/e4a8514ac66619a7d0fe228f5108612c3e0d265e)
=> add user_query_history

application/nlq/data_access/database.py
[add get hive comment](https://github.com/aws-samples/generative-bi-using-rag/commit/d6d2e0b6fb57666bcd4bc4844c1ba129fc72ba3a)
=> add get hive comment

application/api/main.py, application/api/schemas.py, application/api/service.py, application/nlq/business/connection.py, application/nlq/business/log_feedback.py, application/nlq/business/log_store.py, application/nlq/business/model.py, application/nlq/business/profile.py, application/nlq/business/vector_store.py, application/nlq/core/chat_context.py, application/nlq/core/state_machine.py, application/nlq/data_access/database.py, application/pages/1_🌍_Generative_BI_Playground.py, application/utils/llm.py, application/utils/logging.py, application/utils/tool.py
=> merge v1.7.0 to v1.8.0

README.md, source/resources/bin/main.ts, source/resources/cdk-config.json, source/resources/lib/aos/aos-stack.ts, source/resources/lib/cognito/cognito-stack.ts, source/resources/lib/ecs/ecs-stack.ts, source/resources/lib/main-stack.ts
[support specifying bedrock region](https://github.com/aws-samples/generative-bi-using-rag/commit/eeb47f16ed64fbd73bb3160010042c4154d0b8b0)
=> support specifying bedrock region

application/nlq/business/connection.py, application/nlq/data_access/database.py, application/pages/2_🪙_Data_Connection_Management.py, application/utils/apis.py
[add bigquery](https://github.com/aws-samples/generative-bi-using-rag/commit/3327b4f1e9a4d8d602a35f0f62b7bb7f752f0237)
=> add bigquery support

application/api/service.py, application/nlq/business/log_store.py
[remove some code](https://github.com/aws-samples/generative-bi-using-rag/commit/b8f563e8c5f4d1546d12c1d692e2fef55fad691a)
=> remove some code

application/pages/mainpage.py, application/utils/prompts/check_prompt.py
[add model id check](https://github.com/aws-samples/generative-bi-using-rag/commit/b9ce92ec0b761b66f365a31a9ccb1ca847f895f4)
=> add model id check

application/nlq/business/datasource/base.py, application/tests/unit_tests/test_row_level_security.py
=> improve the logic of replacing table name in the original SQL

application/api/service.py, source/resources/package.json
[add state Generating Suggested Questions](https://github.com/aws-samples/generative-bi-using-rag/commit/1af59afba155f7e55513eb3192fe0774afd3c494)
=> add state Generating Suggested Questions

application/utils/apis.py, application/utils/llm.py
[add isinstance type judge](https://github.com/aws-samples/generative-bi-using-rag/commit/a3290dcf1674c5901b4346ab08563b271446be55)
=> add isinstance type judge

source/resources/lib/ecs/ecs-stack.ts
[add DeleteSecret](https://github.com/aws-samples/generative-bi-using-rag/commit/f01b90a00730ff3fe0c95933f625017ce9c2524a)
=> add DeleteSecret

source/resources/lib/aos/aos-stack.ts
[change guid](https://github.com/aws-samples/generative-bi-using-rag/commit/e4d75581f7599bca422feefda26726d8ecd939cb)
=> change guid

application/utils/apis.py, application/utils/llm.py
[change data visual](https://github.com/aws-samples/generative-bi-using-rag/commit/1b4d6c44581b65fea844c06b91e53e08c8f4daf2)
=> change data visual

application/nlq/core/state_machine.py, application/pages/6_📚_Index_Management.py, application/pages/7_📚_Entity_Management.py, application/pages/8_📚_Agent_Cot_Management.py
[add index management](https://github.com/aws-samples/generative-bi-using-rag/commit/dab790a2392c5b2828672eb1cfb3f74178cf7177)
=> add index management

application/pages/8_📚_Agent_Cot_Management.py
[fix cot_refresh_view error](https://github.com/aws-samples/generative-bi-using-rag/commit/1785c8cdc81b3b906e81262b64dcdf0889ddb66e)
=> fix cot_refresh_view error

application/utils/llm.py
[fix search_data data type](https://github.com/aws-samples/generative-bi-using-rag/commit/5752a41b9c0cea73508c8db1851f482f43b88814)
=> fix search_data data type

README.md, README_CN.md, application/pages/mainpage.py
[add workshop](https://github.com/aws-samples/generative-bi-using-rag/commit/24bf2d2c75dfe9575cb2474796ba1f98016546ef)
=> add workshop

application/utils/apis.py
[fix bug](https://github.com/aws-samples/generative-bi-using-rag/commit/21928c7f3cd45b05726fbc6b906d63323132065c)
=> fix some issue

application/utils/llm.py
[change None to model_response](https://github.com/aws-samples/generative-bi-using-rag/commit/26327ba8aa713f6eb735d19f78b67dd14e548ef4)
=> change None to  model_response

application/nlq/data_access/database.py, application/pages/2_🪙_Data_Connection_Management.py
[add presto support](https://github.com/aws-samples/generative-bi-using-rag/commit/ca1133cea94b4f5740877addc5c8adf305191e1b)
=> add presto support

application/main.py, application/nlq/data_access/database.py, application/utils/llm.py
[add fix some issue](https://github.com/aws-samples/generative-bi-using-rag/commit/8aee8dca19ae39017d6b657822d49086698ee551)
=> add fix some issue
