aws-samples/generative-bi-using-rag

- application/pages/1_🌍_Natural_Language_Querying.py
- application/requirements.txt
- application/utils/llm.py
- application/utils/prompt.py
- add intent code, refuse to answer irrelevant questions
- change text input and show history query
> add intent code and change text input 

- .gitignore
- README.md
- source/resources/.npmignore
- source/resources/README.md
- source/resources/bin/main.ts
- source/resources/cdk.json
- source/resources/jest.config.js
- source/resources/lib/ec2/ec2-stack.ts
- source/resources/lib/ec2/user_data/install_docker.sh
- source/resources/lib/ec2/user_data/setup_app.sh
- source/resources/lib/main-stack.ts
- source/resources/package.json
- source/resources/tsconfig.json
- Add Code for Deployment Using AWS CDK
> feat: add cdk deploy code

- application/pages/1_🌍_Natural_Language_Querying.py
- application/utils/llm.py
- application/utils/prompts/generate_prompt.py
> fix some error

- application/utils/prompts/generate_prompt.py
> change prompt

- application/api/schemas.py
- application/api/service.py
- application/nlq/business/nlq_chain.py
- application/pages/1_🌍_Natural_Language_Querying.py
- application/utils/apis.py
- application/utils/domain.py
- application/utils/llm.py
- application/utils/opensearch.py
- application/utils/tool.py
> code refactoring

- application/api/service.py
- application/utils/prompts/generate_prompt.py
- data_visualization_system_prompt_dict
> add data_visualization_system_prompt_dict

- application/api/main.py
- application/api/schemas.py
- application/api/service.py
- application/pages/1_🌍_Generative_BI_Playground.py
> add user_feedback_upvote

- application/nlq/business/vector_store.py
- application/nlq/data_access/opensearch.py
> add delete same query

- application/api/main.py
- application/api/service.py
- application/utils/prompts/check_prompt.py
- application/utils/prompts/generate_prompt.py
> add user_feedback_downvote

- application/utils/prompt.py
…he statement is ---- In the process of generating SQL statements, please do not use aliases.
If aliases used in the SQL statements, it will result in the error, for example, use int as the alias of the table interactions.
Thus changed the mysql prompt to fix the problem.
[issue-fixed-doc.docx](https://github.com/user-attachments/files/15760041/issue-fixed-doc.docx)
> Add this statement in mysql prompt to fix the generating SQL error. 

- application/Dockerfile
- application/Dockerfile-api
- application/initial_data/README.md
- source/resources/lib/aos/aos-stack.ts
- source/resources/lib/ecs/ecs-stack.ts
- [change Dockerfile source](https://github.com/aws-samples/generative-bi-using-rag/commit/39c74c0aa4854511d2a3303e2ed68c7923e7286d)
> change Dockerfile source

- report-front-end/src/common/api/WebSocket.ts
- report-front-end/src/components/chatbot-panel/custom-questions.tsx
- report-front-end/src/components/config-panel/index.tsx
> bug fix for sample questions

- application/api/main.py
- application/api/service.py
- [remove some code and replace space in SQL](https://github.com/aws-samples/generative-bi-using-rag/commit/2551c9d3b911880128bc67e517e5aa11276122af)
> remove some code and replace space in SQL

- application/Dockerfile
- application/Dockerfile-api
- application/Index.py
- application/pages/5_🪙_Prompt_Management.py
- application/utils/navigation.py
[add force_set_cookie](https://github.com/aws-samples/generative-bi-using-rag/commit/c6f44ec0bf57a794783f83930b2728377679bdc1)
> add force_set_cookie

- README.md
- application/api/main.py
- application/api/schemas.py
- application/api/service.py
- application/main.py
- application/nlq/business/log_store.py
- application/nlq/business/vector_store.py
- application/nlq/data_access/dynamo_query_log.py
- application/nlq/data_access/opensearch.py
- application/pages/1_🌍_Generative_BI_Playground.py
- application/pages/6_📚_Index_Management.py
- application/pages/7_📚_Entity_Management.py
- application/requirements.txt
- application/utils/llm.py
- application/utils/opensearch.py
- application/utils/prompt.py
- application/utils/tool.py
[change code for multi chat](https://github.com/aws-samples/generative-bi-using-rag/commit/ce87a302d750ebf509e853ada659edac70b05997)
> change code for multi chat

- application/api/service.py
[add sql error Regenerating](https://github.com/aws-samples/generative-bi-using-rag/commit/571b1dcbc9e9e737a197fe225f5385782f478be3)
> add sql error  Regenerating

- application/nlq/data_access/database.py
- application/requirements-api.txt
- application/requirements.txt
[add sqlalchemy-redshift](https://github.com/aws-samples/generative-bi-using-rag/commit/92b80bb82ca97ca84365679e39fb35a49a678bd1)
> add sqlalchemy-redshift

- application/pages/1_🌍_Generative_BI_Playground.py
[change do_visualize_results](https://github.com/aws-samples/generative-bi-using-rag/commit/9daf1cb1eca8c9abcc10a1927d6f1e42828fb6d9)
> change do_visualize_results

- application/utils/tool.py
[change convert_timestamps_to_str](https://github.com/aws-samples/generative-bi-using-rag/commit/6e38678226b3f2507c513353cc32cb6cdf6c3d2a)
> change convert_timestamps_to_str

- application/nlq/core/state_machine.py
- application/pages/1_🌍_Generative_BI_Playground.py
[add get_generated_sql_explain](https://github.com/aws-samples/generative-bi-using-rag/commit/2fcf8b965ca615ae2f226a65881cb980470f329a)
> add get_generated_sql_explain

- application/nlq/core/state_machine.py
[add data visualization](https://github.com/aws-samples/generative-bi-using-rag/commit/ba7ddf2debadc7a29196008a8fd90e41c927bed3)
> add data visualization

- application/api/main.py
- application/api/schemas.py
- application/api/service.py
- application/nlq/business/connection.py
- application/nlq/business/log_feedback.py
- application/nlq/business/log_store.py
- application/nlq/business/model.py
- application/nlq/business/profile.py
- application/nlq/business/vector_store.py
[add log feedback](https://github.com/aws-samples/generative-bi-using-rag/commit/910b04d0b7062f04d8a1b2092a8f126313208965)
> add log feedback

- application/api/main.py
- application/api/schemas.py
- application/api/service.py
- application/nlq/business/connection.py
- application/nlq/business/log_feedback.py
- application/nlq/business/log_store.py
- application/nlq/business/model.py
- application/nlq/business/profile.py
- application/nlq/business/vector_store.py
- application/nlq/core/chat_context.py
- application/nlq/core/state_machine.py
- application/nlq/data_access/database.py
- application/pages/1_🌍_Generative_BI_Playground.py
- application/utils/llm.py
- application/utils/logging.py
- application/utils/tool.py
> merge v1.8.0
